### ISSUE TITLE
Fa 5.13 and 5.11.2 

### ISSUE THREAD

**Issue by g7sim** [so-diao/tinymce-fontawesomepicker#1]
Great tool !!!  But most users will use the free version of 5.13  and not the pro-version. Can You publish 2 versions ?

(What also can be and should be  added is : fontsize, color and spin.  FA5 is not FA4 : It has much more possibilities : See https://www.typesettercms.com/Plugins/338_Font_Awesome_5_Icons)

**Comment by yodagg** [comment]
@g7sim 
Sorry, I used the wrong version.
It has been updated to 5.13.0. `build/package.json`

Good idea. change the font size and color can temporarily use 'forecolor fontsizeselect'. [example](http://gitpages.wo2.me/tinymce-fontawesomepicker/)

I will add 'fontawesome-icon' right click menu 'fontsize color spin'   (when I am free):wink::wink:

**Comment by yodagg** [comment]
v1.0.0 supports right click to open the settings panel.  [example](https://gitpages.wo2.me/tinymce-fontawesomepicker)

![image](https://user-images.githubusercontent.com/24741025/93544897-b0341980-f991-11ea-9fa5-a2be6f0014a2.png)
